eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
springGurungMicroservices:
  endpoints:
    endpoint:
      ORDER-SERVICE:
        url: lb://PAYMENT-SERVICE/payment/get-hello-from-payment
        
        
resilience4j:
  circuitbreaker:
    instances:
      orderServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      userService:
        maxRetryAttempts: 5
        waitDuration: 10s

spring:
  zipkin:
    base-url: http://localhost:9411/

logging:
  file:
    name: C:\Users\suraj\logs\elk-stack.log
  pattern:
    console:

cloud:
  aws:
    credentials:
      profile-name: default
    region:
      auto: true